title: Tony Menzo
description: Research portfolio
theme: just-the-docs

url: https://tonymenzo.github.io/tonymenzo

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/tonymenzo/tonymenzo
